/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import guru.nidi.graphviz.attribute.Label;
import guru.nidi.graphviz.attribute.RankDir;
import guru.nidi.graphviz.attribute.Shape;
import guru.nidi.graphviz.engine.Format;
import guru.nidi.graphviz.engine.Graphviz;
import guru.nidi.graphviz.model.Graph;
import guru.nidi.graphviz.model.MutableGraph;
import guru.nidi.graphviz.model.MutableNode;
import guru.nidi.graphviz.model.Node;

import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;

import static guru.nidi.graphviz.model.Factory.*;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws IOException {
        // Mutable approach
        ArrayList <MutableNode> nodes = new ArrayList<>();
        nodes.add(mutNode("a"));
        nodes.add(mutNode("d"));
        nodes.add(mutNode("e").addLink(nodes.get(0), nodes.get(1)));
        nodes.add(mutNode("a").addLink(to(node("b"))).addLink(to(node("c"))));


        MutableGraph g = mutGraph("example2").setDirected(true);
        for( MutableNode node : nodes) {
            g.add(node);
        }

        // Immutable approach
        ArrayList <Node> nodes1 = new ArrayList<>();
        nodes1.add(node("e").link(to(node("b"))).link(to(node("c"))));
        nodes1.add(node("b").link(to(node("a"))));
        nodes1.add(node("a").link(nodes.get(0), nodes.get(1)));


        Graph g1 = graph("example2").directed();
        for( Node node : nodes1) {
            g1 = g1.with(node);
        }

        File tmpImage = File.createTempFile("tmp", ".png", new File("images/"));
        Graphviz.fromGraph(g).height(1000).render(Format.PNG).toFile(tmpImage);
        Desktop desktop = Desktop.getDesktop();
        desktop.open(tmpImage);
        tmpImage.deleteOnExit();
    }


}
