/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import guru.nidi.graphviz.attribute.Label;
import guru.nidi.graphviz.attribute.RankDir;
import guru.nidi.graphviz.attribute.Shape;
import guru.nidi.graphviz.engine.Format;
import guru.nidi.graphviz.engine.Graphviz;
import guru.nidi.graphviz.model.Graph;

import java.io.File;
import java.io.IOException;

import static guru.nidi.graphviz.model.Factory.*;
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws IOException {
        Graph g = graph("example1").directed()
                .graphAttr().with(RankDir.LEFT_TO_RIGHT)
                .with(

                        node("").with(Shape.POINT).link(to(node("a")).with(Label.of("Test"))),
                        node("a").link(to(node("b")).with(Label.of("Test"))),
                        node("b").link(to(node("c")).with(Label.of("Test"))),
                        node("b").link(to(node("a")).with(Label.of("Test 1"))),
                        node("d").with(Shape.DOUBLE_CIRCLE).link(to(node("c")).with(Label.of("Test")))
                );
        Graphviz.fromGraph(g).height(400).render(Format.PNG).toFile(new File("example/ex1.png"));
    }


}
